LANGUAGES = [
    ("en", "English"),
    ("hi", "हिन्दी"),
    ("mr", "मराठी"),
    ("bn", "বাংলা"),
    ("ta", "தமிழ்"),
    ("te", "తెలుగు"),
    ("gu", "ગુજરાતી"),
    ("kn", "ಕನ್ನಡ"),
    ("ml", "മലയാളം"),
    ("pa", "ਪੰਜਾਬੀ"),
    ("or", "ଓଡ଼ିଆ"),
    ("as", "অসমীয়া"),
    ("ur", "اردو"),
    ("ne", "नेपाली"),
    ("kok", "कोंकणी"),
    ("mai", "मैथिली"),
    ("ks", "کٲشُر"),
    ("sd", "سنڌي"),
    ("sa", "संस्कृतम्"),
    ("mni", "মৈতৈলোন্"),
    ("sat", "ᱥᱟᱱᱛᱟᱲᱤ"),
    ("doi", "डोगरी"),
    ("brx", "बड़ो"),
]

TEXT = {
    "en": {
        "hello": "Hello",
        "site": "Site",
        "city": "City",
        "choose_option": "Choose an option:",
        "current_weather": "Current Weather",
        "forecast_date": "Forecast for a Date",
        "reply_1_2": "Reply with 1 or 2",
        "weather_bot": "Sangreen Renewables Weather Bot",
        "get_current": "Get Current Weather",
        "share_how": "How would you like to share your location?",
        "share_live": "Share Live Location",
        "share_live_rec": "Share Live Location (recommended)",
        "enter_city": "Enter City Name",
        "location_prompt_title": "Share Your Live Location",
        "location_prompt_body": "Tap the attachment button -> Location -> Share Live Location.",
        "city_prompt": "Type your city name (e.g. Mumbai, Pune, Delhi):",
        "forecast_title": "Forecast for a Date",
        "forecast_body": "Enter a date within the next 16 days in DD-MM-YYYY format.",
        "example": "Example",
        "forecast_location": "Location for Forecast",
        "invalid_date": "Invalid date or out of range.\n\nEnter a date within the next 16 days in DD-MM-YYYY format.",
        "back_menu": "Reply *0* to go back to menu.",
        "main_menu": "main menu",
        "reply_main": "Reply *0* for main menu.",
        "unknown": "I didn't understand that. Reply with:",
        "please_reply": "Please reply with:",
        "not_found_city": "Sorry, couldn't find a city named",
        "fetch_weather_error": "Sorry, couldn't fetch weather data right now. Try again later.",
        "no_weather": "Sorry, no weather data available.",
        "fetch_forecast_error": "Sorry, couldn't fetch forecast data.",
        "fetch_hourly_error": "Sorry, couldn't fetch hourly weather data. Try again later.",
        "no_hourly": "No hourly data available for that date.",
        "something_wrong": "Something went wrong. Please start again.",
        "weather_for": "Weather for",
        "live_weather": "Live Weather at Your Site",
        "condition": "Condition",
        "temperature": "Temperature",
        "feels": "feels",
        "humidity": "Humidity",
        "cloud_cover": "Cloud Cover",
        "rain_chance": "Rain Chance",
        "rain": "Rain",
        "pressure": "Pressure",
        "wind_report": "Wind Report",
        "direction": "Direction",
        "ground": "Ground",
        "selected_height": "Selected Height",
        "gusts_ground": "Ground Gusts",
        "wind_speed": "Wind Speed",
        "safe": "Stay safe on site!",
        "hourly_forecast": "Hourly Forecast",
        "date": "Date",
        "time": "Time",
        "temp": "Temp",
        "wind": "Wind",
        "height_question": "Wind speed at which height?",
        "height_hint": "Open-Meteo provides wind at these heights. Reply with 1, 2, 3, or 4.",
        "height_invalid": "Please select a wind height:",
        "language_title": "Please select your language",
        "language_saved": "Language selected",
        "language_hint": "Reply with the language number. Send *language* anytime to change it.",
        "change_language": "Change Language",
        "media_prompt": "Thanks for sharing! For weather, please share your live location via the location attachment button.",
    },
    "hi": {
        "hello": "नमस्ते",
        "site": "साइट",
        "city": "शहर",
        "choose_option": "एक विकल्प चुनें:",
        "current_weather": "वर्तमान मौसम",
        "forecast_date": "तारीख का पूर्वानुमान",
        "reply_1_2": "1 या 2 लिखें",
        "weather_bot": "संग्रीन रिन्यूएबल्स मौसम बॉट",
        "get_current": "वर्तमान मौसम देखें",
        "share_how": "आप लोकेशन कैसे देना चाहेंगे?",
        "share_live": "लाइव लोकेशन शेयर करें",
        "share_live_rec": "लाइव लोकेशन शेयर करें (अनुशंसित)",
        "enter_city": "शहर का नाम लिखें",
        "location_prompt_title": "अपनी लाइव लोकेशन शेयर करें",
        "location_prompt_body": "अटैचमेंट बटन -> Location -> Share Live Location दबाएं.",
        "city_prompt": "अपने शहर का नाम लिखें (जैसे Mumbai, Pune, Delhi):",
        "forecast_title": "तारीख का पूर्वानुमान",
        "forecast_body": "अगले 16 दिनों के अंदर की तारीख DD-MM-YYYY फॉर्मेट में लिखें.",
        "example": "उदाहरण",
        "forecast_location": "पूर्वानुमान के लिए लोकेशन",
        "invalid_date": "तारीख गलत है या सीमा से बाहर है.\n\nअगले 16 दिनों के अंदर की तारीख DD-MM-YYYY फॉर्मेट में लिखें.",
        "back_menu": "मेन्यू पर लौटने के लिए *0* लिखें.",
        "main_menu": "मुख्य मेन्यू",
        "reply_main": "मुख्य मेन्यू के लिए *0* लिखें.",
        "unknown": "मैं समझ नहीं पाया. कृपया लिखें:",
        "please_reply": "कृपया लिखें:",
        "not_found_city": "माफ करें, यह शहर नहीं मिला",
        "fetch_weather_error": "अभी मौसम डेटा नहीं मिल पाया. थोड़ी देर बाद कोशिश करें.",
        "no_weather": "मौसम डेटा उपलब्ध नहीं है.",
        "fetch_forecast_error": "पूर्वानुमान डेटा नहीं मिल पाया.",
        "fetch_hourly_error": "घंटेवार मौसम डेटा नहीं मिल पाया. थोड़ी देर बाद कोशिश करें.",
        "no_hourly": "इस तारीख के लिए घंटेवार डेटा उपलब्ध नहीं है.",
        "something_wrong": "कुछ गलत हुआ. कृपया फिर से शुरू करें.",
        "weather_for": "मौसम",
        "live_weather": "आपकी साइट का लाइव मौसम",
        "condition": "स्थिति",
        "temperature": "तापमान",
        "feels": "महसूस",
        "humidity": "नमी",
        "cloud_cover": "बादल",
        "rain_chance": "बारिश की संभावना",
        "rain": "बारिश",
        "pressure": "दबाव",
        "wind_report": "हवा रिपोर्ट",
        "direction": "दिशा",
        "ground": "जमीन स्तर",
        "selected_height": "चुनी गई ऊंचाई",
        "gusts_ground": "जमीन स्तर के झोंके",
        "wind_speed": "हवा की गति",
        "safe": "साइट पर सुरक्षित रहें!",
        "hourly_forecast": "घंटेवार पूर्वानुमान",
        "date": "तारीख",
        "time": "समय",
        "temp": "तापमान",
        "wind": "हवा",
        "height_question": "हवा की गति किस ऊंचाई पर चाहिए?",
        "height_hint": "Open-Meteo इन ऊंचाइयों पर हवा देता है. 1, 2, 3 या 4 लिखें.",
        "height_invalid": "कृपया हवा की ऊंचाई चुनें:",
        "language_title": "कृपया अपनी भाषा चुनें",
        "language_saved": "भाषा चुनी गई",
        "language_hint": "भाषा का नंबर लिखें. बदलने के लिए कभी भी *language* लिखें.",
        "change_language": "भाषा बदलें",
        "media_prompt": "धन्यवाद! मौसम के लिए कृपया लोकेशन अटैचमेंट से लाइव लोकेशन शेयर करें.",
    },
}

ALIASES = {
    "mr": "hi", "bn": "hi", "ta": "hi", "te": "hi", "gu": "hi", "kn": "hi",
    "ml": "hi", "pa": "hi", "or": "hi", "as": "hi", "ur": "hi", "ne": "hi",
    "kok": "hi", "mai": "hi", "ks": "hi", "sd": "hi", "sa": "hi",
    "mni": "hi", "sat": "hi", "doi": "hi", "brx": "hi",
}

AVAILABLE_LANGUAGES = [(code, name) for code, name in LANGUAGES if code in TEXT]
LANGUAGE_BY_NUMBER = {str(i): code for i, (code, _) in enumerate(AVAILABLE_LANGUAGES, 1)}
LANGUAGE_NAMES = dict(AVAILABLE_LANGUAGES)


def normalize_lang(lang):
    return lang if lang in TEXT else ALIASES.get(lang, "en")


def t(lang, key):
    lang = normalize_lang(lang)
    return TEXT.get(lang, TEXT["en"]).get(key, TEXT["en"].get(key, key))


def language_menu():
    lines = ["🌐 *Please select your language*"]
    lines.append("")
    for i, (code, name) in enumerate(AVAILABLE_LANGUAGES, 1):
        lines.append(f"{i}. {name}")
    lines.append("")
    lines.append("Reply with the number. Example: 1 for English")
    return "\n".join(lines)

